<?php namespace smp_core_podcast_functionality;

function regsiter_acf_post_podcast() {

    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }
    
    $podcast_slug = get_podcast_settings()['slug'];


    acf_add_local_field_group( array(
        'key'               => 'group_6844c5d5cf57f',
        'title'             => 'Single Post Podcast - 2025 ',
        'fields'            => array(
            // Group: Episode URLs
            array(
                'key'               => 'field_6844c5f82ace2',
                'label'             => 'Episode URLs',
                'name'              => 'urls',
                'aria-label'        => '',
                'type'              => 'group',
                'instructions'      => 'Use shortcode: <code>[episode_fields name="urls"]</code>',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                'layout'            => 'block',
                'sub_fields'        => array(
                    // Spotify
                    array(
                        'key'               => 'field_6844c5f82ace3',
                        'label'             => 'Spotify',
                        'name'              => 'spotify',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://open.spotify.com/show/0fHCjIg7f7iJ4ytgMqYSJC" target="_blank">https://open.spotify.com/show/0fHCjIg7f7iJ4ytgMqYSJC</a><br>Shortcode: <code>[episode_fields name="urls_spotify"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // Pandora
                    array(
                        'key'               => 'field_6844c5f82ace4',
                        'label'             => 'Pandora',
                        'name'              => 'pandora',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => 'Use shortcode: <code>[episode_fields name="urls_pandora"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // SoundCloud
                    array(
                        'key'               => 'field_6844c5f82ace5',
                        'label'             => 'SoundCloud',
                        'name'              => 'soundcloud',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => 'HIHI <a href="https://soundcloud.com/mikeyperes" target="_blank">https://soundcloud.com/mikeyperes</a><br>Shortcode: <code>[episode_fields name="urls_soundcloud"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // Google Podcast
                    array(
                        'key'               => 'field_6844c5f82ace6',
                        'label'             => 'Google Podcast',
                        'name'              => 'google',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://podcasts.google.com/feed/aHR0cHM6Ly9wb2RjYXN0Lm1pY2hhZWxwZXJlcy5jb20vZmVlZC9wb2RjYXN0Lw" target="_blank">https://podcasts.google.com/feed/aHR0cHM6Ly9wb2RjYXN0Lm1pY2hhZWxwZXJlcy5jb20vZmVlZC9wb2RjYXN0Lw</a><br>Shortcode: <code>[episode_fields name="urls_google"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // Deezer
                    array(
                        'key'               => 'field_6844c5f82ace7',
                        'label'             => 'Deezer',
                        'name'              => 'deezer',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://www.deezer.com/show/3651277" target="_blank">https://www.deezer.com/show/3651277</a><br>Shortcode: <code>[episode_fields name="urls_deezer"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // Amazon
                    array(
                        'key'               => 'field_6844c5f82ace8',
                        'label'             => 'Amazon',
                        'name'              => 'amazon',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://music.amazon.com/podcasts/d4dba625-8ea3-420e-bb89-d358e6e17605/the-michael-peres-podcast-w-mikey-peres" target="_blank">https://music.amazon.com/podcasts/d4dba625-8ea3-420e-bb89-d358e6e17605/the-michael-peres-podcast-w-mikey-peres</a><br>Shortcode: <code>[episode_fields name="urls_amazon"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // Apple Podcast
                    array(
                        'key'               => 'field_6844c5f82ace9',
                        'label'             => 'Apple Podcast',
                        'name'              => 'apple',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://podcasts.apple.com/us/podcast/the-michael-peres-podcast-w-mikey-peres/id1318140329" target="_blank">https://podcasts.apple.com/us/podcast/the-michael-peres-podcast-w-mikey-peres/id1318140329</a><br>Shortcode: <code>[episode_fields name="urls_apple"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // iHeart
                    array(
                        'key'               => 'field_6844c5f82acea',
                        'label'             => 'iHeart',
                        'name'              => 'iheart',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://www.iheart.com/podcast/269-the-michael-peres-podcast-65366400/" target="_blank">https://www.iheart.com/podcast/269-the-michael-peres-podcast-65366400/</a><br>Shortcode: <code>[episode_fields name="urls_iheart"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // Audible
                    array(
                        'key'               => 'field_6844c5f82aceb',
                        'label'             => 'Audible',
                        'name'              => 'audible',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://www.audible.com/pd/The-Michael-Peres-Podcast-w-Mikey-Peres-Podcast/B09Z8S39QS" target="_blank">https://www.audible.com/pd/The-Michael-Peres-Podcast-w-Mikey-Peres-Podcast/B09Z8S39QS</a><br>Shortcode: <code>[episode_fields name="urls_audible"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // Stitcher
                    array(
                        'key'               => 'field_6844c5f82acec',
                        'label'             => 'Stitcher',
                        'name'              => 'stitcher',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://www.stitcher.com/show/the-michael-peres-podcast" target="_blank">https://www.stitcher.com/show/the-michael-peres-podcast</a><br>Shortcode: <code>[episode_fields name="urls_stitcher"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // Blubrry
                    array(
                        'key'               => 'field_6844c5f82aced',
                        'label'             => 'Blubrry',
                        'name'              => 'blubrry',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://blubrry.com/mikeyperes/" target="_blank">https://blubrry.com/mikeyperes/</a><br>Shortcode: <code>[episode_fields name="urls_blubrry"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // Gaana
                    array(
                        'key'               => 'field_6844c5f82acee',
                        'label'             => 'Gaana',
                        'name'              => 'gaana',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => 'Use shortcode: <code>[episode_fields name="urls_gaana"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // Podchaser
                    array(
                        'key'               => 'field_6844c5f82acef',
                        'label'             => 'Podchaser',
                        'name'              => 'podchaser',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://www.podchaser.com/podcasts/the-michael-peres-podcast-2258457" target="_blank">https://www.podchaser.com/podcasts/the-michael-peres-podcast-2258457</a><br>Shortcode: <code>[episode_fields name="urls_podchaser"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // JioSaavn
                    array(
                        'key'               => 'field_6844c5f82acf0',
                        'label'             => 'JioSaavn',
                        'name'              => 'jiosaavn',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => 'Use shortcode: <code>[episode_fields name="urls_jiosaavn"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // TuneIn
                    array(
                        'key'               => 'field_6844c5f82acf1',
                        'label'             => 'TuneIn',
                        'name'              => 'tunein',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://tunein.com/podcasts/Technology-Podcasts/The-Michael-Peres-Podcast-p1333869/" target="_blank">https://tunein.com/podcasts/Technology-Podcasts/The-Michael-Peres-Podcast-p1333869/</a><br>Shortcode: <code>[episode_fields name="urls_tunein"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // iMDB
                    array(
                        'key'               => 'field_6844c5f82acf2',
                        'label'             => 'iMDB',
                        'name'              => 'imdb',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://www.imdb.com/title/tt16410896/" target="_blank">https://www.imdb.com/title/tt16410896/</a><br>Shortcode: <code>[episode_fields name="urls_imdb"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // Anghami
                    array(
                        'key'               => 'field_6844c5f82acf3',
                        'label'             => 'Anghami',
                        'name'              => 'anghami',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => 'Use shortcode: <code>[episode_fields name="urls_anghami"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // YouTube
                    array(
                        'key'               => 'field_6844c5f82acf4',
                        'label'             => 'YouTube',
                        'name'              => 'youtube',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => '<a href="https://youtube.com/@mikeyperes" target="_blank">https://youtube.com/@mikeyperes</a><br>Shortcode: <code>[episode_fields name="urls_youtube"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // Instagram
                    array(
                        'key'               => 'field_6844c5f82acf5',
                        'label'             => 'Instagram',
                        'name'              => 'instagram',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => 'Use shortcode: <code>[episode_fields name="urls_instagram"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // ListenNotes
                    array(
                        'key'               => 'field_6844c5f82acf6',
                        'label'             => 'ListenNotes',
                        'name'              => 'listennotes',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => 'Use shortcode: <code>[episode_fields name="urls_listennotes"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                    // RSS
                    array(
                        'key'               => 'field_6844c8f60702c',
                        'label'             => 'RSS',
                        'name'              => 'rss',
                        'aria-label'        => '',
                        'type'              => 'text',
                        'instructions'      => 'Use shortcode: <code>[episode_fields name="urls_rss"]</code>',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                        'default_value'     => '',
                        'maxlength'         => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                    ),
                ),
            ),
            // Host(s)
            array(
                'key'               => 'field_6844c7776e21e',
                'label'             => 'Host(s)',
                'name'              => 'hosts',
                'aria-label'        => '',
                'type'              => 'post_object',
                'instructions'      => 'Use shortcode: <code>[episode_fields name="hosts"]</code>',
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                'post_type'         => array( 0=>'profile' ),
                'return_format'     => 'object',
                'multiple'          => 1,
                'allow_null'        => 0,
                'ui'                => 1,
            ),
            // Summary
            array(
                'key'               => 'field_6844c7e536052',
                'label'             => 'Summary',
                'name'              => 'summary',
                'aria-label'        => '',
                'type'              => 'textarea',
                'instructions'      => 'Use shortcode: <code>[episode_fields name="summary"]</code>',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                'default_value'     => '',
                'maxlength'         => '',
                'rows'              => '',
                'placeholder'       => '',
                'new_lines'         => '',
            ),
            // Audio URL
            array(
                'key'               => 'field_6844c7e536056',
                'label'             => 'Audio URL',
                'name'              => 'audio_url',
                'aria-label'        => '',
                'type'              => 'text',
                'instructions'      => 'Use shortcode: <code>[episode_fields name="audio_url"]</code>',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                'default_value'     => '',
                'maxlength'         => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
            ),
            // Audio File
            array(
                'key'               => 'field_6844c7e536050',
                'label'             => 'Audio File',
                'name'              => 'audio',
                'aria-label'        => '',
                'type'              => 'file',
                'instructions'      => 'Use shortcode: <code>[episode_fields name="audio"]</code>',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
				'return_format'  => 'array', 
                'library'           => '',
                'min_size'          => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            // Episode Number
            array(
                'key'               => 'field_6844c7e536051',
                'label'             => 'Episode Number',
                'name'              => 'number',
                'aria-label'        => '',
                'type'              => 'text',
                'instructions'      => 'Use shortcode: <code>[episode_fields name="number"]</code>',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                'default_value'     => '',
                'maxlength'         => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
            ),
            // Active
            array(
                'key'               => 'field_6844c7e536053',
                'label'             => 'Active',
                'name'              => 'active',
                'aria-label'        => '',
                'type'              => 'true_false',
                'instructions'      => 'Use shortcode: <code>[episode_fields name="active"]</code>',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                'message'           => '',
                'default_value'     => 1,
                'ui'                => 0,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),
            // Season
            array(
                'key'               => 'field_6844c7e536054',
                'label'             => 'Season',
                'name'              => 'season',
                'aria-label'        => '',
                'type'              => 'text',
                'instructions'      => 'Use shortcode: <code>[episode_fields name="season"]</code>',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                'default_value'     => '',
                'maxlength'         => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
            ),
            // Duration
            array(
                'key'               => 'field_6844c7e536055',
                'label'             => 'Duration',
                'name'              => 'duration',
                'aria-label'        => '',
                'type'              => 'text',
                'instructions'      => 'Use shortcode: <code>[episode_fields name="duration"]</code>',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                'default_value'     => '',
                'maxlength'         => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
            ),
            // Same As (Schema Dump)
            array(
                'key'               => 'field_6844c7e536058',
                'label'             => 'Same As (Schema Dump)',
                'name'              => 'same_as',
                'aria-label'        => '',
                'type'              => 'textarea',
                'instructions'      => 'Use shortcode: <code>[episode_fields name="same_as"]</code>',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                'default_value'     => '',
                'maxlength'         => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
            ),
            // Citations
            array(
                'key'               => 'field_6844c7e536057',
                'label'             => 'Citations',
                'name'              => 'citations',
                'aria-label'        => '',
                'type'              => 'wysiwyg',
                'instructions'      => 'Use shortcode: <code>[episode_fields name="citations"]</code>',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array( 'width'=>'','class'=>'','id'=>'' ),
                'default_value'     => '',
                'tabs'              => 'all',
                'toolbar'           => 'full',
                'media_upload'      => 1,
                'delay'             => 0,
            ),
        ),
        'location'          => array(
            array( array( 
                'param'=>'post_type',
                'operator'=>'==',
                'value'=>$podcast_slug) ),
        ),
        'menu_order'        => 0,
        'position'          => 'normal',
        'style'             => 'default',
        'label_placement'   => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'    => '',
        'active'            => true,
        'description'       => '',
        'show_in_rest'      => 0,
    ) );

}


function register_post_acf_fields(){

}