<?php

namespace SMP\Podcast\Acf;

final class PodcastOptionsFieldGroup {
    public const GROUP_KEY = 'group_6848b7b0247cc';

    /** @return array<string,mixed> */
    public static function definition( array $field_group = [] ): array {
        unset( $field_group );
        return array(
        'key' => 'group_6848b7b0247cc',
        'title' => 'Podcast Settings',
        'fields' => array(


                   // Import Settings Group
                   array(
                    'key'           => 'field_import_settings_group',
                    'label'         => 'Import Settings',
                    'name'          => 'import_settings',
                    'type'          => 'group',
                    'instructions'  => '',
                    'required'      => 0,
                    'conditional_logic' => 0,
                    'wrapper'       => array('width'=>'','class'=>'','id'=>''),
                    'layout'        => 'block',
                    'sub_fields'    => array(
                        array(
                            'key'       => 'field_import_settings_message',
                            'label'     => '',
                            'name'      => 'import_settings_message',
                            'type'      => 'message',
                            'instructions' => '',
                            'required'  => 0,
                            'conditional_logic' => 0,
                            'wrapper'   => array('width'=>'','class'=>'','id'=>''),
                            'message'   => 'WP All Import and its ACF add-on must be active. Source spreadsheets must be accessible to the importer.',
                            'new_lines' => 'wpautop',
                            'esc_html'  => 0,
                        ),
                    ),
                ),
    
                // Episode Group
                array(
                    'key'           => 'field_episode_group',
                    'label'         => 'Episode',
                    'name'          => 'episode',
                    'type'          => 'group',
                    'instructions'  => '',
                    'required'      => 0,
                    'conditional_logic' => 0,
                    'wrapper'       => array('width'=>'','class'=>'','id'=>''),
                    'layout'        => 'block',
                    'sub_fields'    => array(
                        array(
                            'key'           => 'field_68490cabe88f',
                            'label'         => 'Podcast Episode Google Sheet',
                            'name'          => 'google_sheet_posts',
                            'type'          => 'text',
                            'instructions'  => 'Open <a target="_blank" rel="noopener noreferrer" href="' . esc_url( admin_url( 'admin.php?page=pmxi-admin-manage' ) ) . '">WP All Import</a> to run or update the episode import.',
                            'required'      => 0,
                            'conditional_logic' => 0,
                            'wrapper'       => array('width'=>'','class'=>'','id'=>''),
                            'default_value' => '',
                            'maxlength'     => '',
                            'placeholder'   => '',
                            'prepend'       => '',
                            'append'        => '',
                        ),
                        array(
                            'key'           => 'field_import_settings_episode',
                            'label'         => 'Import Settings',
                            'name'          => 'import_settings_episode',
                            'type'          => 'file',
                            'instructions'  => '',
                            'required'      => 0,
                            'conditional_logic' => 0,
                            'wrapper'       => array('width'=>'','class'=>'','id'=>''),
                            'return_format' => 'url',
                            'library'       => 'all',
                            'min_size'      => '',
                            'max_size'      => '',
                            'mime_types'    => '',
                        ),
                    ),
                ),
    
                // Profiles Group
                array(
                    'key'           => 'field_profiles_group',
                    'label'         => 'Profiles',
                    'name'          => 'profiles',
                    'type'          => 'group',
                    'instructions'  => '',
                    'required'      => 0,
                    'conditional_logic' => 0,
                    'wrapper'       => array('width'=>'','class'=>'','id'=>''),
                    'layout'        => 'block',
                    'sub_fields'    => array(
                        array(
                            'key'           => 'field_68490cabe879f',
                            'label'         => 'Podcast Profiles Google Sheet',
                            'name'          => 'google_sheet_profiles',
                            'type'          => 'text',
                            'instructions'  => 'Open <a target="_blank" rel="noopener noreferrer" href="' . esc_url( admin_url( 'admin.php?page=pmxi-admin-manage' ) ) . '">WP All Import</a> to run or update the profile import.',
                            'required'      => 0,
                            'conditional_logic' => 0,
                            'wrapper'       => array('width'=>'','class'=>'','id'=>''),
                            'default_value' => '',
                            'maxlength'     => '',
                            'placeholder'   => '',
                            'prepend'       => '',
                            'append'        => '',
                        ),
                        array(
                            'key'           => 'field_import_settings_profiles',
                            'label'         => 'Import Settings',
                            'name'          => 'import_settings_profiles',
                            'type'          => 'file',
                            'instructions'  => '',
                            'required'      => 0,
                            'conditional_logic' => 0,
                            'wrapper'       => array('width'=>'','class'=>'','id'=>''),
                            'return_format' => 'url',
                            'library'       => 'all',
                            'min_size'      => '',
                            'max_size'      => '',
                            'mime_types'    => '',
                        ),
                    ),
                ),







            array(
                'key' => 'field_6848b7b0373d3',
                'label' => 'Default Host',
                'name' => 'default_host',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => 'Default host to be automatically selected when a new podcast is created.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'profile',
                ),
                'post_status' => '',
                'taxonomy' => '',
                'return_format' => 'object',
                'multiple' => 0,
                'allow_null' => 1,
                'bidirectional' => 0,
                'ui' => 1,
                'bidirectional_target' => array(),
            ),
            array(
                'key' => 'field_68490cabe8089',
                'label' => 'Podcast URLs',
                'name' => 'podcast_urls',
                'aria-label' => '',
                'type' => 'group',
                'instructions'  => 'Use <code>[podcast_url social="spotify"]</code> with the relevant platform key to output a saved URL.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    /*
                    array(
                        'key' => 'field_68490cabe808a',
                        'label' => 'YouTube',
                        'name' => 'youtube',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="youtube"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),*/
                    array(
                        'key' => 'field_68490cabe808b',
                        'label' => 'Listen Notes',
                        'name' => 'listen_notes',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="listen_notes"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe808c',
                        'label' => 'Spotify',
                        'name' => 'spotify',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="spotify"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe808d',
                        'label' => 'SoundCloud',
                        'name' => 'soundcloud',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="soundcloud"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe808e',
                        'label' => 'Google Podcast',
                        'name' => 'google_podcast',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="google_podcast"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe808f',
                        'label' => 'Apple Podcast',
                        'name' => 'apple_podcast',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="apple_podcast"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe8090',
                        'label' => 'Amazon',
                        'name' => 'amazon',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="amazon"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe8091',
                        'label' => 'Pandora',
                        'name' => 'pandora',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="pandora"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe8092',
                        'label' => 'iHeart',
                        'name' => 'iheart',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="iheart"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe8093',
                        'label' => 'Stitcher',
                        'name' => 'stitcher',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="stitcher"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe8094',
                        'label' => 'Blubrry',
                        'name' => 'blubrry',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="blubrry"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe8095',
                        'label' => 'Podchaser',
                        'name' => 'podchaser',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="podchaser"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe8096',
                        'label' => 'Deezer',
                        'name' => 'deezer',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="deezer"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe8097',
                        'label' => 'TuneIn',
                        'name' => 'tunein',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="tunein"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe8098',
                        'label' => 'Anghami',
                        'name' => 'anghami',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="anghami"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe8099',
                        'label' => 'JioSaavn',
                        'name' => 'jiosaavn',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="jiosaavn"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    /*
                    array(
                        'key' => 'field_68490cabe809a',
                        'label' => 'Instagram',
                        'name' => 'instagram',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="instagram"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),*/
                    array(
                        'key' => 'field_68490cabe809b',
                        'label' => 'RSS',
                        'name' => 'rss',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="rss"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => 'rss',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    /*
                    array(
                        'key' => 'field_68490cabe809d',
                        'label' => 'Facebook',
                        'name' => 'facebook',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="facebook"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),*/
                    array(
                        'key' => 'field_68490cabe809e',
                        'label' => 'INC Verified Profile',
                        'name' => 'inc_verified_profile',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="inc_verified_profile"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe809f',
                        'label' => 'Listen Notes',
                        'name' => 'listen_notes',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="listen_notes"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe80a0',
                        'label' => 'Audible',
                        'name' => 'audible',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="audible"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe80a1',
                        'label' => 'IMDB',
                        'name' => 'imdb',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="imdb"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_68490cabe80a2',
                        'label' => 'Gaana',
                        'name' => 'gaana',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Usage: [podcast_url social="gaana"]',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array('width'=>'','class'=>'','id'=>''),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'theme-options-podcast',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        );
    }

    /** @return array<int,string> */
    public static function field_labels(): array {
        return [
            'Content labels and legacy content slug',
            'Import settings for episodes and profiles',
            'Default host',
            'Podcast platform URLs',
        ];
    }
}
